server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stats
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    ru:
      yandex.practicum: INFO
    org:
      zalando.logbook: TRACE
      hibernate.SQL: DEBUG
      springframework:
        orm.jpa: INFO
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG

