services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    ports:
      - "6543:5432"
    container_name: stats-db
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:16.1
    ports:
      - "6544:5432"
    container_name: ewm-db
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5

#  ewm-service:
#    build: ./main-service
#    container_name: ewm-service
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
#      SPRING_DATASOURCE_USERNAME: dbuser
#      SPRING_DATASOURCE_PASSWORD: 12345
#    depends_on:
#      - ewm-db
