services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports: ["9090:9090"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      stats-db:
        condition: service_healthy


  stats-db:
    image: postgres:16.1
    ports: ["6543:5432"]
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    ports: ["6544:5432"]
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: pg_isready -q -U $$POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    ports: ["8080:8080"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      STATS_SERVER_URL: http://stats-server:9090
    depends_on:
      ewm-db:
        condition: service_healthy

